/* DO NOT EDIT THIS FILE - it is machine generated */
#include "com_example_zx_jnihelloworld_JNIUtils.h"

JNIEXPORT jstring JNICALL Java_com_example_zx_jnihelloworld_JNIUtils_getStrHelloFromC
  (JNIEnv * env, jclass){
  return env -> NewStringUTF("Hello World");
  }

